# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('client_name', models.CharField(max_length=1000, verbose_name='Client name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('importance', models.IntegerField(verbose_name='Importance')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('login', models.CharField(max_length=25, verbose_name='Login')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Phone number')),
                ('born_date', models.DateField(blank=True, default=None, null=True, verbose_name='Born date')),
                ('last_connection', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date of last connection')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('years_seniority', models.IntegerField(default=0, verbose_name='Seniority')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date of Birthday')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taskManager.UserProfile')),
            ],
            bases=('taskManager.userprofile',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taskManager.UserProfile')),
                ('specialisation', models.CharField(max_length=50, verbose_name='Specialisation')),
            ],
            bases=('taskManager.userprofile',),
        ),
        migrations.AddField(
            model_name='task',
            name='app_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManager.UserProfile', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskManager.Project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='developer',
            name='Supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskManager.Supervisor'),
        ),
    ]
