# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='superviso',
            new_name='sup',
        ),
    ]
