# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_auto_20170727_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developerworktask',
            old_name='time_elapsed_dev',
            new_name='time_elapsed',
        ),
    ]
