# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', utils.fields.MultilingualCharField(max_length=200, verbose_name='Title')),
                ('description', utils.fields.MultilingualTextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
